# Generated by Django 5.1.1 on 2024-10-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_member_email_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
