# Generated by Django 5.1.1 on 2024-10-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_date_posted_post_post_catagories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_catagories',
            new_name='post_categories',
        ),
    ]
