# Generated by Django 5.1.1 on 2024-10-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS', 'Friends')], default='EVERYONE', max_length=10),
        ),
    ]
