# Generated by Django 5.1.1 on 2024-10-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_species_pet_animal_alter_shelter_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
