# Generated by Django 5.1.1 on 2024-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_profile_age_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='media/'),
        ),
    ]
