# Generated by Django 5.1.1 on 2024-10-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_pet_post_image_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profile_images/'),
        ),
    ]
