# Generated by Django 5.1.1 on 2024-10-27 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='shelter',
        ),
        migrations.AddField(
            model_name='pet',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='post_image',
            field=models.ImageField(upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdoptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_transaction', to='app.pet')),
            ],
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
    ]
