# Generated by Django 5.1.1 on 2024-10-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_adoptionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
    ]
