# Generated by Django 5.1.1 on 2024-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_adoptionapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptiontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied')], default=0.0013339920948616602, max_length=10),
            preserve_default=False,
        ),
    ]
