# Generated by Django 5.1.1 on 2024-11-15 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionevent',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='adoptionevent',
            name='user',
        ),
        migrations.AddField(
            model_name='adoptionevent',
            name='application',
            field=models.ForeignKey(default=0.0006737333812432626, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.adoptionapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.pet'),
        ),
    ]
