# Generated by Django 5.1.1 on 2024-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_adoptionevent_pet_remove_adoptionevent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionevent',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
