# Generated by Django 5.1.1 on 2024-11-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_adoptionevent_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdoptionEvent',
            new_name='History',
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=20),
        ),
    ]
