# Generated by Django 5.1.1 on 2024-11-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Profile_default.png', null=True, upload_to='profile_images/'),
        ),
    ]
