# Generated by Django 5.1.1 on 2024-11-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_adoptionapplication_pet_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visibility',
        ),
    ]
